### PR TITLE
Seamonkey & Statusbar support

### PR DESCRIPTION
**Pull request by lxle**
Memchaser is one of the few extensions for firefox that doesn't quite work in seamonkey even after being 'converted', being a Seamonkey user I would of course like to see Seamonkey supported and a statusbar option for it to reside in.

### CODE REVIEW

**Comment by whimboo** [comment]
I wonder what we should do with this PR and why git informed me that it has been freshly created. Comments I see here are from 2013? Also the commits list is huge, so maybe you do not have the latest code from master locally.

**Comment by xabolcs** [comment]
@lxle created a PR instead issue. The commit range is `mozilla/0.3..mozilla/master`.

It's a misplaced issue. We should close this PR, and open a separate issue, with the same description.

**Comment by whimboo** [comment]
Sounds good. Would you mind doing it?

**Comment by xabolcs** [comment]
Filed Issue #210 and closing this pull request.

@lxle please continue commenting there!

**Pull request closed without merging**
