### PR TITLE
Depend on mozdownload without any version specified (#234)

### PR DESCRIPTION
**Pull request by xabolcs**
Fix for #234.

### CODE REVIEW

**Comment by whimboo** [comment]
Hm, do we have add-on compatibility changes for SDK type add-ons with Firefox 44?

**Comment by xabolcs** [comment]
> Hm, do we have add-on compatibility changes for SDK type add-ons with Firefox 44?

Sorry?

Do you ask about the failing Nightly and Aurora builds?
If yes, then it seems like. The currently used Addon SDK 1.17 is the latest.

**Comment by whimboo** [comment]
Yes, that was my question. Btw can you reproduce those failures locally too? If yes we might wanna use mozregression to figure out what broke us.

Anyway this failure shouldn't block us to get this PR merged. Feel free to do whenever you have the time for.

**Comment by xabolcs** [comment]
Yes, it's locally reproducible.

As ESR38 supports `jpm` I think it's easier to use it, instead doing a bisect. :)

Will merge this soon. Thanks!

**Comment by xabolcs** [comment]
Btw there are interesting bugs and fixes in [Bugzilla][1]!


[1]: https://bugzilla.mozilla.org/buglist.cgi?quicksearch=Test+output+exceeded+timeout

**Comment by whimboo** [comment]
As long as jpm is working lets simply get it converted then in the other PR.

**Pull request merged**
