### PR TITLE
Add a Help menuitem (#180)

### PR DESCRIPTION
**Pull request by insaynasasin**
added a new link on the content.html page and updated the corresponding action in the main.js file

### CODE REVIEW

**Comment by xabolcs** [comment]
@insaynasasin do you have time to continue this pull request with addressing @whimboo's comment?

**Comment by xabolcs** [comment]
@whimboo, I'd like to continue this PR (ok, not this, but an another, based on this) after the other logging related PRs got merged.

**Comment by whimboo** [comment]
The logging PRs have been merged. So I think we are good to go here?

**Comment by xabolcs** [comment]
Sure.

Should I open a new PR, addressing your comments?

**Comment by xabolcs** [comment]
Merged to PR #220, comments addressed.

Closing.

**Pull request closed without merging**
